from swiss import SwissEngine
from player import Player
import math

input_players = (
        Player(name='Alice',
               score=1,
               pairing_no=1,
               opponents=(2,),
               colour_hist=(1,),
               rating=2300),
        Player(name='Pablo',
                score=0,
pairing_no=2,
               opponents=(1,3,4,5,7,8,9,),
        #opponents=(1,),
               colour_hist=(-1,),
               rating=2200),
        Player(name='Qba',
               rating=2100,
pairing_no=3,
                score=1,
               opponents=(4,),
               colour_hist=(1,)),
        Player(name='Tester',
               rating=2000,
pairing_no=4,
                score=0,
               opponents=(3,),
               colour_hist=(-1,)),
                Player(name='ktos',
               rating=1900,
pairing_no=5,
                score=1,
                opponents=(0,),
                colour_hist=(0,),
                       ),
Player(name='Draw1',
               rating=2155,
pairing_no=6,
                score=2.5,
                opponents=(88,),
                colour_hist=(1,),
                       ),
Player(name='Draw2',
               rating=2166,
pairing_no=7,
                score=2.5,
                opponents=(99,),
                colour_hist=(-1,),
                       ),
        Player(name='Halfa1',
               rating=2366,
pairing_no=8,
                score=0.5,
                opponents=(9,),
                colour_hist=(1,),
                       ),
Player(name='Half2',
               rating=2389,
pairing_no=9,
                score=0.5,
                opponents=(8,),
                colour_hist=(-1,),
                       )

)

engine = SwissEngine(2, input_players)



